#服务端口
server:
  port: 18080

spring:
  application:
    name: tanhua-app-server

  redis:  #redis配置
    port: 6379
    host: 192.168.50.132
    database: 1

  cloud:  #nacos配置
    nacos:
      discovery:
        server-addr: 192.168.50.132:8848


dubbo:    #dubbo配置
  registry:
    address: spring-cloud://localhost
  consumer:
    check: false

#smms:
#  token: g2mGk3t0SYEoU1DYbf6DFqt45MXHZT1C

tanhua:
#  mail:
#    user: sunxiaopeng878903@163.com
#    password: XXMEGSMVBCTBFEKA
  #默认推荐列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88
  oss:
    accessKey: HpN449gfOMcoMN-rIHJSn9AeytT93J1-gIjXzA1C
    secretKey: 5KnapnnIufROw0phi-o9LIc860JIgxj69kEcO6Eb
    bucket: image0921
    filePlace: myproject-tanhua
    url: http://rxxokggp3.hn-bkt.clouddn.com/
  huanxin:
    appkey: 1172230814175953#demo
    client-id: YXA6mHOiluFHRWOyPFWIlQNm6g
    client-secret: YXA62XFO70soH088FjjgB9JFzRLzmh8