server:
  port: 18082
spring:
  application:
    name: tanhua-dubbop-mongo
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.132:8848
  data:
    mongodb:
      uri: mongodb://192.168.50.132:27017/tanhua

dubbo:
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.wsj.mongo.apiImpl  #dubbo中包扫描
